version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - C:\Users\luisa\.ollama:/root/.ollama
    restart: unless-stopped
